INSERT INTO roles (role_name)
VALUES 
  ('Admin'),
  ('Organizer');

INSERT INTO state (stname) VALUES
  ('Andhra Pradesh'),
  ('Arunachal Pradesh'),
  ('Assam'),
  ('Bihar'),
  ('Chhattisgarh'),
  ('Goa'),
  ('Gujarat'),
  ('Haryana'),
  ('Himachal Pradesh'),
  ('Jharkhand'),
  ('Karnataka'),
  ('Kerala'),
  ('Madhya Pradesh'),
  ('Maharashtra'),
  ('Manipur'),
  ('Meghalaya'),
  ('Mizoram'),
  ('Nagaland'),
  ('Odisha'),
  ('Punjab'),
  ('Rajasthan'),
  ('Sikkim'),
  ('Tamil Nadu'),
  ('Telangana'),
  ('Tripura'),
  ('Uttar Pradesh'),
  ('Uttarakhand'),
  ('West Bengal'),
  ('Andaman and Nicobar Islands'),
  ('Chandigarh'),
  ('Dadra and Nagar Haveli and Daman and Diu'),
  ('Delhi'),
  ('Jammu and Kashmir'),
  ('Ladakh'),
  ('Lakshadweep'),
  ('Puducherry');


INSERT INTO city (cityname, stid) VALUES
  ('Mumbai', 14),
  ('Pune', 14),
  ('Nagpur', 14),
  ('Nashik', 14),
  ('Aurangabad', 14),
  ('Bengaluru', 11),
  ('Mysuru', 11),
  ('Mangaluru', 11),
  ('Hubli', 11),
  ('Belgaum', 11),
  ('Chennai', 23),
  ('Coimbatore', 23),
  ('Madurai', 23),
  ('Tiruchirappalli', 23),
  ('Salem', 23),
  ('New Delhi', 32),
  ('Dwarka', 32),
  ('Rohini', 32),
  ('Saket', 32),
  ('Karol Bagh', 32),
  ('Kolkata', 28),
  ('Howrah', 28),
  ('Durgapur', 28),
  ('Siliguri', 28),
  ('Asansol', 28);
